/**
 * 区分値マスタ
 */
export class SegmentValueMst {
  public static readonly SegmentValue: {
    [K in SegmentNameType]: SegmentType[];
  } = {
    // 会社種別
    KAISHA_TYPE: [
      { value: 1, nm: 'ハウスメーカー', sort: 10 },
      { value: 2, nm: '工務店', sort: 20 },
      { value: 3, nm: '設計事務所', sort: 30 },
    ],
    // 取扱い工法区分
    TORIATSUKAI_KUBUN: [
      { value: 1, nm: '木造軸組工法（在来工法）', sort: 10 },
      {
        value: 2,
        nm: '２×４・２×６工法（ツーバイフォー・ツーバイシックス工法）',
        sort: 20,
      },
      { value: 3, nm: '鉄筋コンクリート造（RC造）', sort: 30 },
      { value: 4, nm: '重量鉄骨造', sort: 40 },
      { value: 5, nm: '木質系プレハブ工法', sort: 50 },
      { value: 6, nm: '鉄骨系プレハブ工法（軽量鉄骨造）', sort: 60 },
      { value: 7, nm: 'コンクリート系プレハブ工法', sort: 70 },
      { value: 8, nm: 'その他', sort: 80 },
    ],
    // 会社の特徴種別
    TOKUCHOU_TYPE: [
      { value: 1, nm: 'オンライン相談可', sort: 10 },
      { value: 2, nm: '地元に密着', sort: 20 },
      { value: 3, nm: 'アフターサポートが充実', sort: 30 },
      { value: 4, nm: '土地探しの相談可', sort: 40 },
      { value: 5, nm: 'インテリアの相談可', sort: 50 },
      { value: 6, nm: 'ファイナンシャルプランナーに相談可', sort: 60 },
      { value: 7, nm: '住宅ローン紹介可', sort: 70 },
    ],
    // 公開状態
    KOUKAI_JOUTAI: [
      { value: 1, nm: '下書き', sort: 10 },
      { value: 2, nm: '公開', sort: 20 },
      { value: 3, nm: '非公開', sort: 30 },
    ],
    // 店舗・モデルハウス区分
    TENPO_MODEL_HOUSE_KUBUN: [
      { value: 1, nm: '店舗', sort: 10 },
      { value: 2, nm: 'モデルハウス', sort: 20 },
    ],
    // 店舗・モデルハウスタグ
    TENPO_MODEL_HOUSE_TAG: [
      { value: 1, nm: 'ローコスト住宅', typeValue: 1, type: '価格', sort: 10 },
      {
        value: 2,
        nm: 'ハイグレード住宅',
        typeValue: 1,
        type: '価格',
        sort: 20,
      },
      { value: 3, nm: '平屋建築', typeValue: 2, type: '構造', sort: 30 },
      { value: 4, nm: '3階建て以上', typeValue: 2, type: '構造', sort: 40 },
      { value: 5, nm: '狭小住宅', typeValue: 2, type: '構造', sort: 50 },
      {
        value: 6,
        nm: 'ユニバーサルデザイン',
        typeValue: 3,
        type: '性能',
        sort: 60,
      },
      {
        value: 7,
        nm: '高耐震・免振・制震',
        typeValue: 3,
        type: '性能',
        sort: 70,
      },
      { value: 8, nm: '高気密・高断熱', typeValue: 3, type: '性能', sort: 80 },
      { value: 9, nm: '防音・遮音', typeValue: 3, type: '性能', sort: 90 },
      { value: 10, nm: 'ZEH住宅', typeValue: 3, type: '性能', sort: 100 },
      { value: 11, nm: 'エコ・省エネ', typeValue: 3, type: '性能', sort: 110 },
      {
        value: 12,
        nm: '賃貸・店舗併用住宅',
        typeValue: 3,
        type: '性能',
        sort: 120,
      },
      {
        value: 13,
        nm: '共働き・子育て世帯',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 130,
      },
      {
        value: 14,
        nm: '二世帯・多世帯',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 140,
      },
      {
        value: 15,
        nm: 'バリアフリー',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 150,
      },
      {
        value: 16,
        nm: '20代・30代で建てる',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 160,
      },
      {
        value: 17,
        nm: 'セカンドライフ',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 170,
      },
      {
        value: 18,
        nm: '別荘・リゾートハウス',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 180,
      },
      {
        value: 19,
        nm: 'ペットと一緒に暮らす',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 190,
      },
      { value: 20, nm: '和風な家', typeValue: 5, type: 'イメージ', sort: 200 },
      { value: 21, nm: '輸入住宅', typeValue: 5, type: 'イメージ', sort: 210 },
      {
        value: 22,
        nm: '木・自然素材の家',
        typeValue: 5,
        type: 'イメージ',
        sort: 220,
      },
      { value: 23, nm: 'モダン', typeValue: 6, type: 'デザイン', sort: 230 },
      {
        value: 24,
        nm: 'クラシック',
        typeValue: 6,
        type: 'デザイン',
        sort: 240,
      },
      {
        value: 25,
        nm: 'エレガント',
        typeValue: 6,
        type: 'デザイン',
        sort: 250,
      },
      { value: 26, nm: 'ミニマル', typeValue: 6, type: 'デザイン', sort: 260 },
      { value: 27, nm: '木造軸組', typeValue: 7, type: '工法', sort: 270 },
      { value: 28, nm: '2×4・2×6', typeValue: 7, type: '工法', sort: 280 },
      {
        value: 29,
        nm: 'RC（鉄筋コンクリート)造',
        typeValue: 7,
        type: '工法',
        sort: 290,
      },
      { value: 30, nm: '重量鉄骨', typeValue: 7, type: '工法', sort: 300 },
      {
        value: 31,
        nm: '鉄骨系プレハブ',
        typeValue: 7,
        type: '工法',
        sort: 310,
      },
      {
        value: 32,
        nm: '木質系プレハブ',
        typeValue: 7,
        type: '工法',
        sort: 320,
      },
      {
        value: 33,
        nm: 'コンクリート系プレハブ',
        typeValue: 7,
        type: '工法',
        sort: 330,
      },
      { value: 34, nm: 'その他', typeValue: 7, type: '工法', sort: 340 },
      {
        value: 35,
        nm: 'オンライン相談可',
        typeValue: 8,
        type: '会社の特徴',
        sort: 350,
      },
      {
        value: 36,
        nm: '地元に密着',
        typeValue: 8,
        type: '会社の特徴',
        sort: 360,
      },
      {
        value: 37,
        nm: 'アフターサポートが充実',
        typeValue: 8,
        type: '会社の特徴',
        sort: 370,
      },
      {
        value: 38,
        nm: '土地探しの相談可',
        typeValue: 8,
        type: '会社の特徴',
        sort: 380,
      },
      {
        value: 39,
        nm: 'インテリアの相談可',
        typeValue: 8,
        type: '会社の特徴',
        sort: 390,
      },
      {
        value: 40,
        nm: 'フィナンシャルプランナーに相談可',
        typeValue: 8,
        type: '会社の特徴',
        sort: 400,
      },
      {
        value: 41,
        nm: '住宅ローンに紹介',
        typeValue: 8,
        type: '会社の特徴',
        sort: 410,
      },
    ],
    // 間取り区分
    MADORI_KUBUN: [
      { value: 104, nm: '1LDK以下', sort: 10 },
      { value: 105, nm: '2K', sort: 20 },
      { value: 106, nm: '2DK', sort: 30 },
      { value: 107, nm: '2LDK', sort: 40 },
      { value: 108, nm: '3K', sort: 50 },
      { value: 109, nm: '3DK', sort: 60 },
      { value: 110, nm: '3LDK', sort: 70 },
      { value: 111, nm: '4K', sort: 80 },
      { value: 112, nm: '4DK', sort: 90 },
      { value: 113, nm: '4LDK', sort: 100 },
      { value: 114, nm: '5K', sort: 110 },
      { value: 115, nm: '5DK', sort: 120 },
      { value: 116, nm: '5LDK以上', sort: 130 },
    ],
    // 階数区分
    KAISUU_KUBUN: [
      { value: 1, nm: '平屋', sort: 10 },
      { value: 2, nm: '2階', sort: 20 },
      { value: 3, nm: '3階以上', sort: 30 },
    ],
    // 家族構成種別
    KAZOKU_KOUSEI_TYPE: [
      { value: 1, nm: '夫婦単身', sort: 10 },
      { value: 2, nm: '夫婦+子ども', sort: 20 },
      { value: 3, nm: '3世代以上', sort: 30 },
      { value: 4, nm: 'その他', sort: 40 },
    ],
    // 事例タグ
    JIREI_TAG: [
      { value: 1, nm: '平屋', typeValue: 1, type: '構造', sort: 10 },
      { value: 2, nm: '３階建て以上', typeValue: 1, type: '構造', sort: 20 },
      { value: 3, nm: '狭小住宅', typeValue: 1, type: '構造', sort: 30 },
      {
        value: 4,
        nm: '高耐震・免震・制震',
        typeValue: 2,
        type: '性能',
        sort: 40,
      },
      { value: 5, nm: '高気密・高断熱', typeValue: 2, type: '性能', sort: 50 },
      { value: 6, nm: '防音・遮音', typeValue: 2, type: '性能', sort: 60 },
      { value: 7, nm: 'ZEH住宅', typeValue: 2, type: '性能', sort: 70 },
      { value: 8, nm: 'エコ・省エネ', typeValue: 2, type: '性能', sort: 80 },
      {
        value: 9,
        nm: 'ユニバーサルデザイン',
        typeValue: 2,
        type: '性能',
        sort: 90,
      },
      {
        value: 10,
        nm: '賃貸・店舗併用住宅',
        typeValue: 2,
        type: '性能',
        sort: 100,
      },
      {
        value: 11,
        nm: '共働き・子育て世帯',
        typeValue: 3,
        type: 'ライフスタイル',
        sort: 110,
      },
      {
        value: 12,
        nm: '20代・30代で建てる',
        typeValue: 3,
        type: 'ライフスタイル',
        sort: 120,
      },
      {
        value: 13,
        nm: '二世帯・多世帯住宅',
        typeValue: 3,
        type: 'ライフスタイル',
        sort: 130,
      },
      {
        value: 14,
        nm: 'セカンドライフ',
        typeValue: 3,
        type: 'ライフスタイル',
        sort: 140,
      },
      {
        value: 15,
        nm: '別荘・リゾートハウス',
        typeValue: 3,
        type: 'ライフスタイル',
        sort: 150,
      },
      {
        value: 16,
        nm: 'ペットと一緒に暮らす',
        typeValue: 3,
        type: 'ライフスタイル',
        sort: 160,
      },
      {
        value: 17,
        nm: '子育てしやすい',
        typeValue: 4,
        type: 'こだわり',
        sort: 170,
      },
      {
        value: 18,
        nm: '家事が楽になる',
        typeValue: 4,
        type: 'こだわり',
        sort: 180,
      },
      { value: 19, nm: '収納充実', typeValue: 4, type: 'こだわり', sort: 190 },
      {
        value: 20,
        nm: 'ガレージ付き',
        typeValue: 4,
        type: 'こだわり',
        sort: 200,
      },
      {
        value: 21,
        nm: 'キッチンが充実',
        typeValue: 4,
        type: 'こだわり',
        sort: 210,
      },
      { value: 22, nm: '屋上あり', typeValue: 4, type: 'こだわり', sort: 220 },
      {
        value: 23,
        nm: '地下室あり',
        typeValue: 4,
        type: 'こだわり',
        sort: 230,
      },
      {
        value: 24,
        nm: '庭を楽しむ',
        typeValue: 4,
        type: 'こだわり',
        sort: 240,
      },
      { value: 25, nm: '和風な家', typeValue: 5, type: 'イメージ', sort: 250 },
      { value: 26, nm: '輸入住宅', typeValue: 5, type: 'イメージ', sort: 260 },
      {
        value: 27,
        nm: '木・自然素材の家',
        typeValue: 5,
        type: 'イメージ',
        sort: 270,
      },
      { value: 28, nm: 'モダン', typeValue: 6, type: 'デザイン', sort: 280 },
      {
        value: 29,
        nm: 'クラシック',
        typeValue: 6,
        type: 'デザイン',
        sort: 290,
      },
      {
        value: 30,
        nm: 'エレガント',
        typeValue: 6,
        type: 'デザイン',
        sort: 300,
      },
      { value: 31, nm: 'ミニマル', typeValue: 6, type: 'デザイン', sort: 310 },
    ],
    // 建築事例画像タグ
    JIREI_TYPE: [
      { value: 1, nm: 'I型キッチン', sort: 10 },
      { value: 2, nm: 'II型キッチン', sort: 20 },
      { value: 3, nm: 'キッチン', sort: 30 },
      { value: 4, nm: 'システムキッチン', sort: 40 },
      { value: 5, nm: 'カウンターキッチン', sort: 50 },
      { value: 6, nm: 'オープンキッチン', sort: 60 },
      { value: 7, nm: 'L型キッチン', sort: 70 },
      { value: 8, nm: 'オーダーキッチン', sort: 80 },
      { value: 9, nm: 'ペニンシュラキッチン', sort: 90 },
      { value: 10, nm: 'トイレ', sort: 100 },
      { value: 11, nm: 'トイレカウンター', sort: 110 },
      { value: 12, nm: 'タンクレストイレ', sort: 120 },
      { value: 13, nm: '洗面台', sort: 130 },
      { value: 14, nm: '洗面所', sort: 140 },
      { value: 15, nm: '玄関', sort: 150 },
      { value: 16, nm: '土間', sort: 160 },
      { value: 17, nm: 'カーポート', sort: 170 },
      { value: 18, nm: 'ビルトインガレージ', sort: 180 },
      { value: 19, nm: 'ガレージハウス', sort: 190 },
      { value: 20, nm: 'リビング', sort: 200 },
      { value: 21, nm: 'ダイニング', sort: 210 },
      { value: 22, nm: 'リビングダイニング', sort: 220 },
      { value: 23, nm: 'ユニットバス', sort: 230 },
      { value: 24, nm: 'お風呂', sort: 240 },
      { value: 25, nm: 'シャワールーム', sort: 250 },
      { value: 26, nm: 'ジャグジー', sort: 260 },
      { value: 27, nm: '24時間換気', sort: 270 },
      { value: 28, nm: '換気扇', sort: 280 },
      { value: 29, nm: '暖炉', sort: 290 },
      { value: 30, nm: '掘りごたつ', sort: 300 },
      { value: 31, nm: '床暖房', sort: 310 },
      { value: 32, nm: 'ダウンライト', sort: 320 },
      { value: 33, nm: 'エレベーター', sort: 330 },
      { value: 34, nm: '天井', sort: 340 },
      { value: 35, nm: '勾配天井', sort: 350 },
      { value: 36, nm: '折り上げ天井', sort: 360 },
      { value: 37, nm: '窓', sort: 370 },
      { value: 38, nm: '天窓', sort: 380 },
      { value: 39, nm: '掃出し窓', sort: 390 },
      { value: 40, nm: '床', sort: 400 },
      { value: 41, nm: '床の間', sort: 410 },
      { value: 42, nm: '琉球畳', sort: 420 },
      { value: 43, nm: 'フローリング', sort: 430 },
      { value: 44, nm: '畳', sort: 440 },
      { value: 45, nm: 'タイル壁', sort: 450 },
      { value: 46, nm: '壁', sort: 460 },
      { value: 47, nm: '外壁', sort: 470 },
      { value: 48, nm: '内壁', sort: 480 },
      { value: 49, nm: 'ウォークインクローゼット', sort: 490 },
      { value: 50, nm: 'クローゼット', sort: 500 },
      { value: 51, nm: '押入れ', sort: 510 },
      { value: 52, nm: 'パントリー', sort: 520 },
      { value: 53, nm: '物置小屋', sort: 530 },
      { value: 54, nm: '屋根裏収納', sort: 540 },
      { value: 55, nm: '床下収納', sort: 550 },
      { value: 56, nm: 'シューズクローク', sort: 560 },
      { value: 57, nm: 'ペット（犬）', sort: 570 },
      { value: 58, nm: 'ペット（猫）', sort: 580 },
      { value: 59, nm: 'ペット（その他）', sort: 590 },
      { value: 60, nm: 'キャットウォーク', sort: 600 },
      { value: 61, nm: '子供部屋', sort: 610 },
      { value: 62, nm: '寝室', sort: 620 },
      { value: 63, nm: 'ランドリールーム', sort: 630 },
      { value: 64, nm: '地下室', sort: 640 },
      { value: 65, nm: '半地下', sort: 650 },
      { value: 66, nm: 'ワークスペース', sort: 660 },
      { value: 67, nm: '屋根裏部屋', sort: 670 },
      { value: 68, nm: 'ロフト', sort: 680 },
      { value: 69, nm: '自家発電', sort: 690 },
      { value: 70, nm: '省エネルギー', sort: 700 },
      { value: 71, nm: '蓄電池', sort: 710 },
      { value: 72, nm: 'HEMS', sort: 720 },
      { value: 73, nm: '庭', sort: 730 },
      { value: 74, nm: '中庭', sort: 740 },
      { value: 75, nm: '縁側', sort: 750 },
      { value: 76, nm: 'エクステリア', sort: 760 },
      { value: 77, nm: 'ガーデンルーム', sort: 770 },
      { value: 78, nm: 'ウッドデッキ', sort: 780 },
      { value: 79, nm: 'ルーフバルコニー', sort: 790 },
      { value: 80, nm: '勝手口', sort: 800 },
      { value: 81, nm: '生垣', sort: 810 },
      { value: 82, nm: 'ピロティ', sort: 820 },
      { value: 83, nm: '坪庭', sort: 830 },
      { value: 84, nm: '軒下', sort: 840 },
      { value: 85, nm: '雨どい', sort: 850 },
      { value: 86, nm: '雨戸', sort: 860 },
      { value: 87, nm: '屋上', sort: 870 },
      { value: 88, nm: 'ベランダ', sort: 880 },
      { value: 89, nm: 'ルーバー', sort: 890 },
      { value: 90, nm: '階段', sort: 900 },
      { value: 91, nm: '螺旋階段', sort: 910 },
      { value: 92, nm: '瓦屋根', sort: 920 },
      { value: 93, nm: '切妻屋根', sort: 930 },
      { value: 94, nm: '屋根', sort: 940 },
      { value: 95, nm: '陸屋根', sort: 950 },
      { value: 96, nm: '白', sort: 960 },
      { value: 97, nm: '黒', sort: 970 },
      { value: 98, nm: 'ピンク', sort: 980 },
      { value: 99, nm: 'オレンジ', sort: 990 },
      { value: 100, nm: '赤', sort: 1000 },
      { value: 101, nm: '青', sort: 1010 },
      { value: 102, nm: '緑', sort: 1020 },
      { value: 103, nm: '黄色', sort: 1030 },
      { value: 104, nm: 'グレー', sort: 1040 },
      { value: 105, nm: 'パステル', sort: 1050 },
      { value: 106, nm: 'カラフル', sort: 1060 },
      { value: 107, nm: 'モノトーン', sort: 1070 },
      { value: 108, nm: '大理石', sort: 1080 },
      { value: 109, nm: 'ビーチ', sort: 1090 },
      { value: 110, nm: 'チェリー', sort: 1100 },
      { value: 111, nm: 'メープル', sort: 1110 },
      { value: 112, nm: 'モルタル', sort: 1120 },
      { value: 113, nm: 'オーク', sort: 1130 },
      { value: 114, nm: 'ガラス', sort: 1140 },
      { value: 115, nm: '漆喰', sort: 1150 },
      { value: 116, nm: 'アイアン', sort: 1160 },
      { value: 117, nm: '断熱材', sort: 1170 },
      { value: 118, nm: 'スチール', sort: 1180 },
      { value: 119, nm: 'チーク', sort: 1190 },
      { value: 120, nm: 'ウォールナット', sort: 1200 },
      { value: 121, nm: 'マホガニー', sort: 1210 },
      { value: 122, nm: '鉄骨造', sort: 1220 },
      { value: 123, nm: 'メタル', sort: 1230 },
      { value: 124, nm: '木曽檜', sort: 1240 },
      { value: 125, nm: 'ラタン', sort: 1250 },
      { value: 126, nm: 'パイン', sort: 1260 },
      { value: 127, nm: 'ブラックチェリー', sort: 1270 },
      { value: 128, nm: 'コンクリート', sort: 1280 },
      { value: 129, nm: '無垢材', sort: 1290 },
      { value: 130, nm: '引戸', sort: 1300 },
      { value: 131, nm: '飾り棚', sort: 1310 },
      { value: 132, nm: 'バーカウンター', sort: 1320 },
      { value: 133, nm: 'アクセントクロス', sort: 1330 },
      { value: 134, nm: 'ホール', sort: 1340 },
      { value: 135, nm: '障子', sort: 1350 },
      { value: 136, nm: 'サッシ', sort: 1360 },
      { value: 137, nm: 'アプローチ', sort: 1370 },
      { value: 138, nm: '吹抜け', sort: 1380 },
      { value: 139, nm: 'デッドスペース', sort: 1390 },
      { value: 140, nm: 'イタリアン', sort: 1400 },
      { value: 141, nm: 'かわいい', sort: 1410 },
      { value: 142, nm: 'ミニマリスト', sort: 1420 },
      { value: 143, nm: 'DIY', sort: 1430 },
      { value: 144, nm: 'オシャレ', sort: 1440 },
      { value: 145, nm: 'クラシック', sort: 1450 },
      { value: 146, nm: 'かっこいい', sort: 1460 },
      { value: 147, nm: 'ボタニカル', sort: 1470 },
      { value: 148, nm: 'レトロ', sort: 1480 },
      { value: 149, nm: 'アラベスク', sort: 1490 },
      { value: 150, nm: 'ブルックリン', sort: 1500 },
      { value: 151, nm: 'モダン', sort: 1510 },
      { value: 152, nm: 'シック', sort: 1520 },
      { value: 153, nm: 'スケルトン', sort: 1530 },
      { value: 154, nm: 'クール', sort: 1540 },
      { value: 155, nm: 'チューダー', sort: 1550 },
      { value: 156, nm: 'ロココ', sort: 1560 },
      { value: 157, nm: 'アジアン', sort: 1570 },
      { value: 158, nm: 'スマートホーム', sort: 1580 },
      { value: 159, nm: 'セカンドハウス', sort: 1590 },
      { value: 160, nm: 'スタイリッシュ', sort: 1600 },
      { value: 161, nm: 'ミッドセンチュリー', sort: 1610 },
      { value: 162, nm: 'コロニアル', sort: 1620 },
      { value: 163, nm: 'シャビーシック', sort: 1630 },
      { value: 164, nm: 'モダニズム', sort: 1640 },
      { value: 165, nm: 'サーファーズ', sort: 1650 },
      { value: 166, nm: 'レトロモダン', sort: 1660 },
      { value: 167, nm: '南欧風', sort: 1670 },
      { value: 168, nm: 'ジョージアン', sort: 1680 },
      { value: 169, nm: 'ホテル風', sort: 1690 },
      { value: 170, nm: '洋館', sort: 1700 },
      { value: 171, nm: '豪邸', sort: 1710 },
      { value: 172, nm: '京町屋', sort: 1720 },
      { value: 173, nm: 'ログハウス', sort: 1730 },
      { value: 174, nm: '外構', sort: 1740 },
      { value: 175, nm: '梁', sort: 1750 },
      { value: 176, nm: '母屋', sort: 1760 },
      { value: 177, nm: '打ちっぱなし', sort: 1770 },
      { value: 178, nm: '眺望', sort: 1780 },
      { value: 179, nm: '廊下', sort: 1790 },
    ],
    // イベント種別
    EVENT_TYPE: [
      { value: 1, nm: '完成見学会', sort: 10 },
      { value: 2, nm: '構造・工場見学会', sort: 20 },
      { value: 3, nm: '入居者宅見学会', sort: 30 },
      { value: 4, nm: 'モデルルーム・ショールーム見学', sort: 40 },
      { value: 5, nm: '土地相談会', sort: 50 },
      { value: 6, nm: '資金相談会', sort: 60 },
      { value: 7, nm: 'プラン・間取り相談会', sort: 70 },
      { value: 8, nm: '売却・住み替え相談会', sort: 80 },
      { value: 9, nm: '宿泊体験会', sort: 90 },
      { value: 10, nm: 'DIY体験', sort: 100 },
      { value: 11, nm: 'フェア', sort: 110 },
    ],
    // イベント特徴
    EVENT_TOKUCHOU: [
      { value: 1, nm: '初心者向け', sort: 10 },
      { value: 2, nm: '予約不要', sort: 20 },
      { value: 3, nm: '営業お断りOK', sort: 30 },
      { value: 4, nm: '特典あり', sort: 40 },
      { value: 5, nm: '子ども歓迎', sort: 50 },
      { value: 6, nm: 'キッズルームあり', sort: 60 },
      { value: 7, nm: '授乳室あり', sort: 70 },
      { value: 8, nm: '駐車場有', sort: 80 },
    ],
    // カタログ種別
    CATALOG_TYPE: [
      { value: 1, nm: '総合カタログ', sort: 10 },
      { value: 2, nm: '商品別カタログ', sort: 20 },
      { value: 3, nm: '施工実例集', sort: 30 },
    ],
    // お問い合わせ内容種別
    TOIAWASE_NAIYOU: [
      { value: 1, nm: 'すべて', sort: 10 },
      { value: 2, nm: 'カタログ反響', sort: 20 },
      { value: 3, nm: '来店・見学反響', sort: 30 },
      { value: 4, nm: 'イベント反響', sort: 40 },
      { value: 5, nm: '問い合わせ反響', sort: 50 },
    ],
    // ステータス
    STATUS: [
      { value: 1, nm: '新規受付', sort: 10 },
      { value: 2, nm: '確認済み', sort: 20 },
    ],
    // 建築予定地種別
    KENCHIKU_YOTEICHI_TYPE: [
      { value: 1, nm: '現住所と同じ', sort: 10 },
      { value: 2, nm: '予定地・希望地', sort: 20 },
      { value: 3, nm: '決まっていない', sort: 30 },
    ],
    // ユーザー状態
    USER_JOUTAI: [
      { value: 1, nm: '有効', sort: 10 },
      { value: 2, nm: '無効', sort: 20 },
    ],
    // 免許区分
    MENKYO_KUBUN: [{ value: 1, nm: '知事', sort: 10 }],
    // 有無区分
    MENKYO_UMU_KUBUN: [],
    // カタログタグ
    CATALOG_TAG: [
      { value: 1, nm: 'ローコスト住宅', typeValue: 1, type: '価格', sort: 10 },
      {
        value: 2,
        nm: 'ハイグレード住宅',
        typeValue: 1,
        type: '価格',
        sort: 20,
      },
      { value: 3, nm: '平屋建築', typeValue: 2, type: '構造', sort: 30 },
      { value: 4, nm: '3階建て以上', typeValue: 2, type: '構造', sort: 40 },
      { value: 5, nm: '狭小住宅', typeValue: 2, type: '構造', sort: 50 },
      {
        value: 6,
        nm: 'ユニバーサルデザイン',
        typeValue: 3,
        type: '性能',
        sort: 60,
      },
      {
        value: 7,
        nm: '高耐震・免振・制震',
        typeValue: 3,
        type: '性能',
        sort: 70,
      },
      { value: 8, nm: '高気密・高断熱', typeValue: 3, type: '性能', sort: 80 },
      { value: 9, nm: '防音・遮音', typeValue: 3, type: '性能', sort: 90 },
      { value: 10, nm: 'ZEH住宅', typeValue: 3, type: '性能', sort: 100 },
      { value: 11, nm: 'エコ・省エネ', typeValue: 3, type: '性能', sort: 110 },
      {
        value: 12,
        nm: '賃貸・店舗併用住宅',
        typeValue: 3,
        type: '性能',
        sort: 120,
      },
      {
        value: 13,
        nm: '共働き・子育て世帯',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 130,
      },
      {
        value: 14,
        nm: '二世帯・多世帯',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 140,
      },
      {
        value: 15,
        nm: 'バリアフリー',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 150,
      },
      {
        value: 16,
        nm: '20代・30代で建てる',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 160,
      },
      {
        value: 17,
        nm: 'ZEHセカンドライフ',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 170,
      },
      {
        value: 18,
        nm: '別荘・リゾートハウス',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 180,
      },
      {
        value: 19,
        nm: 'ペットと一緒に暮らす',
        typeValue: 4,
        type: 'ライフスタイル',
        sort: 190,
      },
      { value: 20, nm: '玄関', typeValue: 5, type: 'スペース', sort: 200 },
      { value: 21, nm: 'キッチン', typeValue: 5, type: 'スペース', sort: 210 },
      { value: 22, nm: '収納', typeValue: 5, type: 'スペース', sort: 220 },
      { value: 23, nm: 'ガレージ', typeValue: 5, type: 'スペース', sort: 230 },
      {
        value: 24,
        nm: 'エクステリア',
        typeValue: 5,
        type: 'スペース',
        sort: 240,
      },
      { value: 25, nm: '内装', typeValue: 5, type: 'スペース', sort: 250 },
      { value: 26, nm: '外装', typeValue: 5, type: 'スペース', sort: 260 },
      { value: 27, nm: '構造', typeValue: 5, type: 'スペース', sort: 270 },
      { value: 28, nm: '和風な家', typeValue: 6, type: 'イメージ', sort: 280 },
      { value: 29, nm: '輸入住宅', typeValue: 6, type: 'イメージ', sort: 290 },
      {
        value: 30,
        nm: '木・自然素材の家',
        typeValue: 6,
        type: 'イメージ',
        sort: 300,
      },
      { value: 31, nm: 'モダン', typeValue: 7, type: 'デザイン', sort: 310 },
      {
        value: 32,
        nm: 'クラシック',
        typeValue: 7,
        type: 'デザイン',
        sort: 320,
      },
      {
        value: 33,
        nm: 'エレガント',
        typeValue: 7,
        type: 'デザイン',
        sort: 330,
      },
      { value: 34, nm: 'ミニマル', typeValue: 7, type: 'デザイン', sort: 340 },
      { value: 35, nm: '木造軸組', typeValue: 8, type: '工法', sort: 350 },
      { value: 36, nm: '2×4・2×6', typeValue: 8, type: '工法', sort: 360 },
      {
        value: 37,
        nm: 'RC（鉄筋コンクリート）造',
        typeValue: 8,
        type: '工法',
        sort: 370,
      },
      { value: 38, nm: '重量鉄骨', typeValue: 8, type: '工法', sort: 380 },
      {
        value: 39,
        nm: '鉄骨系プレハブ',
        typeValue: 8,
        type: '工法',
        sort: 390,
      },
      {
        value: 40,
        nm: '木質系プレハブ',
        typeValue: 8,
        type: '工法',
        sort: 400,
      },
      {
        value: 41,
        nm: 'コンクリート系プレハブ',
        typeValue: 8,
        type: '工法',
        sort: 410,
      },
      { value: 42, nm: 'その他', typeValue: 8, type: '工法', sort: 420 },
      {
        value: 43,
        nm: '住宅展示場・モデルハウスあり',
        typeValue: 9,
        type: 'その他',
        sort: 430,
      },
      { value: 44, nm: '価格掲載', typeValue: 9, type: 'その他', sort: 440 },
    ],
    // 建築業許可番号区分
    KENSETSU_KYOKA_KUBUN: [
      { value: 0, nm: '国土交通大臣', sort: 10 },
      { value: 1, nm: '知事', sort: 20 },
    ],
    // アットホームユーザーロール
    AT_USER_ROLE: [
      { value: 1, nm: '管理者', sort: 10 },
      { value: 2, nm: '代行入力', sort: 20 },
      { value: 3, nm: '営業担当', sort: 30 },
      { value: 4, nm: '開発', sort: 40 },
    ],
    // 曜日
    YOUBI_KUBUN: [
      { value: 1, nm: '日曜日', sort: 10 },
      { value: 2, nm: '月曜日', sort: 20 },
      { value: 3, nm: '火曜日', sort: 30 },
      { value: 4, nm: '水曜日', sort: 40 },
      { value: 5, nm: '木曜日', sort: 50 },
      { value: 6, nm: '金曜日', sort: 60 },
      { value: 7, nm: '土曜日', sort: 70 },
    ],
    // カタログメディア
    CATALOG_MEDIA: [
      { value: 1, nm: '書籍', sort: 10 },
      { value: 2, nm: 'Web', sort: 20 },
      { value: 3, nm: '動画', sort: 30 },
    ],
    // 展示の内容
    TENJI_NAIYOU: [
      { value: 1, nm: '最新テクノロジー', sort: 10 },
      { value: 2, nm: '建材見本が充実', sort: 20 },
      { value: 3, nm: 'こだわりのインテリア', sort: 30 },
      { value: 4, nm: '建築家デザイン', sort: 40 },
    ],
    // 価格帯From
    KAKAKUTAI_FROM: [
      { value: 1500, nm: '1500万円', sort: 10 },
      { value: 2000, nm: '2000万円', sort: 20 },
      { value: 3000, nm: '3000万円', sort: 30 },
      { value: 3500, nm: '3500万円', sort: 40 },
      { value: 4000, nm: '4000万円', sort: 50 },
    ],
    // 価格帯To
    KAKAKUTAI_TO: [
      { value: 1499, nm: '1499万円', sort: 10 },
      { value: 1999, nm: '1999万円', sort: 20 },
      { value: 2999, nm: '2999万円', sort: 30 },
      { value: 3499, nm: '3499万円', sort: 40 },
      { value: 3999, nm: '3999万円', sort: 50 },
    ],
    // 関心がある項目種別
    KANSHIN_KOUMOKU_TYPE: [
      { value: 1, nm: 'オンラインで相談したい', sort: 10 },
      { value: 2, nm: '設計プランについて相談したい', sort: 20 },
      { value: 3, nm: 'カタログ・資料について相談したい', sort: 30 },
      { value: 4, nm: 'インテリアについて相談したい', sort: 40 },
      {
        value: 5,
        nm: 'ファイナンシャルプランナーにアドバイスしてほしい',
        sort: 50,
      },
      { value: 6, nm: '住宅ローンについて相談したい', sort: 60 },
      { value: 7, nm: 'その他', sort: 70 },
    ],
    // 建築会社ユーザーロール
    KENCHIKU_KAISHA_USER_ROLE: [
      { value: 1, nm: '管理者', sort: 10 },
      { value: 2, nm: '一般', sort: 20 },
    ],
    // アットホームユーザー権限
    AT_USER_KENGEN: [
      { value: 1, nm: '閲覧のみ', sort: 10 },
      { value: 2, nm: '登録・変更・削除可能', sort: 20 },
      { value: 3, nm: 'お知らせ登録のみ', sort: 30 },
    ],
    // 建築工法区分
    KENCHIKU_KOUHOU_KUBUN: [
      { value: 1, nm: '木造軸組工法（在来工法）', sort: 10 },
      {
        value: 2,
        nm: '2×4・2×6工法（ツーバイフォー・ツーバイシックス工法）',
        sort: 20,
      },
      { value: 3, nm: '鉄筋コンクリート造（RC造）', sort: 30 },
      { value: 4, nm: '重量鉄骨造', sort: 40 },
      { value: 5, nm: '木質系プレハブ工法', sort: 50 },
      { value: 6, nm: '鉄骨系プレハブ工法（軽量鉄骨造）', sort: 60 },
      { value: 7, nm: 'コンクリート系プレハブ工法', sort: 70 },
      { value: 8, nm: '独自認定工法など', sort: 80 },
      { value: 9, nm: '独自開発の構造物金物を用いて建築された家', sort: 90 },
    ],
  };
}

/**
 *コード区分名称
 */
export type SegmentNameType =
  | 'KAISHA_TYPE'
  | 'TORIATSUKAI_KUBUN'
  | 'TOKUCHOU_TYPE'
  | 'KOUKAI_JOUTAI'
  | 'TENPO_MODEL_HOUSE_KUBUN'
  | 'TENPO_MODEL_HOUSE_TAG'
  | 'MADORI_KUBUN'
  | 'KAISUU_KUBUN'
  | 'KAZOKU_KOUSEI_TYPE'
  | 'JIREI_TAG'
  | 'JIREI_TYPE'
  | 'EVENT_TYPE'
  | 'EVENT_TOKUCHOU'
  | 'CATALOG_TYPE'
  | 'TOIAWASE_NAIYOU'
  | 'STATUS'
  | 'KENCHIKU_YOTEICHI_TYPE'
  | 'USER_JOUTAI'
  | 'MENKYO_KUBUN'
  | 'MENKYO_UMU_KUBUN'
  | 'CATALOG_TAG'
  | 'KENSETSU_KYOKA_KUBUN'
  | 'AT_USER_ROLE'
  | 'YOUBI_KUBUN'
  | 'CATALOG_MEDIA'
  | 'TENJI_NAIYOU'
  | 'KAKAKUTAI_FROM'
  | 'KAKAKUTAI_TO'
  | 'KANSHIN_KOUMOKU_TYPE'
  | 'KENCHIKU_KAISHA_USER_ROLE'
  | 'AT_USER_KENGEN'
  | 'KENCHIKU_KOUHOU_KUBUN';

/**
 * コード区分値の型
 */
export interface SegmentType {
  value: number;
  nm: string;
  typeValue?: number;
  type?: string;
  sort: number;
}
